# permissions for end users to view collectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: collector-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pinpoint-operator
    app.kubernetes.io/part-of: pinpoint-operator
    app.kubernetes.io/managed-by: kustomize
  name: collector-viewer-role
rules:
- apiGroups:
  - pinpoint.veverita7.github.io
  resources:
  - collectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pinpoint.veverita7.github.io
  resources:
  - collectors/status
  verbs:
  - get
